# Generated by Django 5.1.6 on 2026-01-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('surname', models.TextField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
